"""Add role table..

Revision ID: 99309898597c
Revises: 3eb753256456
Create Date: 2024-12-18 18:15:08.199591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99309898597c'
down_revision = '3eb753256456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('role_id', 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('role')
    # ### end Alembic commands ###
